// Hand-curated seed catalogue. Hex codes come from each team's published
// brand guide where one exists, otherwise from the consensus colour code
// used across the major sports-colour reference sites. Wikipedia titles
// are the article slug — the scraper resolves these to an infobox SVG.
//
// Rosters reflect the 2025-26 season for European football; the US Big
// Four rosters are stable across recent seasons.

import type { SeedTeam } from './types.ts';
import { CFB_TEAMS } from './teams-cfb.ts';
import { NCAAB_TEAMS } from './teams-ncaab.ts';
import { WNBA_TEAMS } from './teams-wnba.ts';

export const TEAMS: SeedTeam[] = [
  ...CFB_TEAMS,
  ...NCAAB_TEAMS,
  ...WNBA_TEAMS,
  // ============ NFL ============
  { id: 'nfl-cardinals',   sport: 'american-football', league: 'NFL', name: 'Arizona Cardinals',     wikipediaTitle: 'Arizona Cardinals',     colors: ['#97233F', '#000000', '#FFB612', '#A5ACAF'] },
  { id: 'nfl-falcons',     sport: 'american-football', league: 'NFL', name: 'Atlanta Falcons',       wikipediaTitle: 'Atlanta Falcons',       colors: ['#A71930', '#000000', '#A5ACAF'] },
  { id: 'nfl-ravens',      sport: 'american-football', league: 'NFL', name: 'Baltimore Ravens',      wikipediaTitle: 'Baltimore Ravens',      colors: ['#241773', '#000000', '#9E7C0C'] },
  { id: 'nfl-bills',       sport: 'american-football', league: 'NFL', name: 'Buffalo Bills',         wikipediaTitle: 'Buffalo Bills',         colors: ['#00338D', '#C60C30'] },
  { id: 'nfl-panthers',    sport: 'american-football', league: 'NFL', name: 'Carolina Panthers',     wikipediaTitle: 'Carolina Panthers',     colors: ['#0085CA', '#101820', '#BFC0BF'] },
  { id: 'nfl-bears',       sport: 'american-football', league: 'NFL', name: 'Chicago Bears',         wikipediaTitle: 'Chicago Bears',         colors: ['#0B162A', '#C83803'] },
  { id: 'nfl-bengals',     sport: 'american-football', league: 'NFL', name: 'Cincinnati Bengals',    wikipediaTitle: 'Cincinnati Bengals',    colors: ['#FB4F14', '#000000'] },
  { id: 'nfl-browns',      sport: 'american-football', league: 'NFL', name: 'Cleveland Browns',      wikipediaTitle: 'Cleveland Browns',      colors: ['#311D00', '#FF3C00'] },
  { id: 'nfl-cowboys',     sport: 'american-football', league: 'NFL', name: 'Dallas Cowboys',        wikipediaTitle: 'Dallas Cowboys',        colors: ['#003594', '#869397', '#041E42'] },
  { id: 'nfl-broncos',     sport: 'american-football', league: 'NFL', name: 'Denver Broncos',        wikipediaTitle: 'Denver Broncos',        colors: ['#FB4F14', '#002244'] },
  { id: 'nfl-lions',       sport: 'american-football', league: 'NFL', name: 'Detroit Lions',         wikipediaTitle: 'Detroit Lions',         colors: ['#0076B6', '#B0B7BC', '#000000'] },
  { id: 'nfl-packers',     sport: 'american-football', league: 'NFL', name: 'Green Bay Packers',     wikipediaTitle: 'Green Bay Packers',     colors: ['#203731', '#FFB612'] },
  { id: 'nfl-texans',      sport: 'american-football', league: 'NFL', name: 'Houston Texans',        wikipediaTitle: 'Houston Texans',        colors: ['#03202F', '#A71930'] },
  { id: 'nfl-colts',       sport: 'american-football', league: 'NFL', name: 'Indianapolis Colts',    wikipediaTitle: 'Indianapolis Colts',    colors: ['#002C5F', '#A2AAAD'] },
  { id: 'nfl-jaguars',     sport: 'american-football', league: 'NFL', name: 'Jacksonville Jaguars',  wikipediaTitle: 'Jacksonville Jaguars',  colors: ['#006778', '#101820', '#9F792C'] },
  { id: 'nfl-chiefs',      sport: 'american-football', league: 'NFL', name: 'Kansas City Chiefs',    wikipediaTitle: 'Kansas City Chiefs',    colors: ['#E31837', '#FFB81C'] },
  { id: 'nfl-raiders',     sport: 'american-football', league: 'NFL', name: 'Las Vegas Raiders',     wikipediaTitle: 'Las Vegas Raiders',     colors: ['#000000', '#A5ACAF'] },
  { id: 'nfl-chargers',    sport: 'american-football', league: 'NFL', name: 'Los Angeles Chargers',  wikipediaTitle: 'Los Angeles Chargers',  colors: ['#0080C6', '#FFC20E', '#002A5E'] },
  { id: 'nfl-rams',        sport: 'american-football', league: 'NFL', name: 'Los Angeles Rams',      wikipediaTitle: 'Los Angeles Rams',      colors: ['#003594', '#FFA300', '#FFFFFF'] },
  { id: 'nfl-dolphins',    sport: 'american-football', league: 'NFL', name: 'Miami Dolphins',        wikipediaTitle: 'Miami Dolphins',        colors: ['#008E97', '#FC4C02', '#005778'] },
  { id: 'nfl-vikings',     sport: 'american-football', league: 'NFL', name: 'Minnesota Vikings',     wikipediaTitle: 'Minnesota Vikings',     colors: ['#4F2683', '#FFC62F'] },
  { id: 'nfl-patriots',    sport: 'american-football', league: 'NFL', name: 'New England Patriots',  wikipediaTitle: 'New England Patriots',  colors: ['#002244', '#C60C30', '#B0B7BC'] },
  { id: 'nfl-saints',      sport: 'american-football', league: 'NFL', name: 'New Orleans Saints',    wikipediaTitle: 'New Orleans Saints',    colors: ['#101820', '#D3BC8D'] },
  { id: 'nfl-giants',      sport: 'american-football', league: 'NFL', name: 'New York Giants',       wikipediaTitle: 'New York Giants',       colors: ['#0B2265', '#A71930', '#A5ACAF'] },
  { id: 'nfl-jets',        sport: 'american-football', league: 'NFL', name: 'New York Jets',         wikipediaTitle: 'New York Jets',         colors: ['#125740', '#000000', '#FFFFFF'] },
  { id: 'nfl-eagles',      sport: 'american-football', league: 'NFL', name: 'Philadelphia Eagles',   wikipediaTitle: 'Philadelphia Eagles',   colors: ['#004C54', '#A5ACAF', '#000000'] },
  { id: 'nfl-steelers',    sport: 'american-football', league: 'NFL', name: 'Pittsburgh Steelers',   wikipediaTitle: 'Pittsburgh Steelers',   colors: ['#101820', '#FFB612', '#C60C30'] },
  { id: 'nfl-49ers',       sport: 'american-football', league: 'NFL', name: 'San Francisco 49ers',   wikipediaTitle: 'San Francisco 49ers',   colors: ['#AA0000', '#B3995D'] },
  { id: 'nfl-seahawks',    sport: 'american-football', league: 'NFL', name: 'Seattle Seahawks',      wikipediaTitle: 'Seattle Seahawks',      colors: ['#002244', '#69BE28', '#A5ACAF'] },
  { id: 'nfl-buccaneers',  sport: 'american-football', league: 'NFL', name: 'Tampa Bay Buccaneers',  wikipediaTitle: 'Tampa Bay Buccaneers',  colors: ['#D50A0A', '#34302B', '#FF7900'] },
  { id: 'nfl-titans',      sport: 'american-football', league: 'NFL', name: 'Tennessee Titans',      wikipediaTitle: 'Tennessee Titans',      colors: ['#0C2340', '#4B92DB', '#C8102E'] },
  { id: 'nfl-commanders',  sport: 'american-football', league: 'NFL', name: 'Washington Commanders', wikipediaTitle: 'Washington Commanders', colors: ['#5A1414', '#FFB612'] },

  // ============ NBA ============
  { id: 'nba-hawks',         sport: 'basketball', league: 'NBA', name: 'Atlanta Hawks',          wikipediaTitle: 'Atlanta Hawks',          colors: ['#E03A3E', '#C1D32F', '#26282A'] },
  { id: 'nba-celtics',       sport: 'basketball', league: 'NBA', name: 'Boston Celtics',         wikipediaTitle: 'Boston Celtics',         colors: ['#007A33', '#BA9653', '#000000'] },
  { id: 'nba-nets',          sport: 'basketball', league: 'NBA', name: 'Brooklyn Nets',          wikipediaTitle: 'Brooklyn Nets',          colors: ['#000000', '#FFFFFF'] },
  { id: 'nba-hornets',       sport: 'basketball', league: 'NBA', name: 'Charlotte Hornets',      wikipediaTitle: 'Charlotte Hornets',      colors: ['#1D1160', '#00788C', '#A1A1A4'] },
  { id: 'nba-bulls',         sport: 'basketball', league: 'NBA', name: 'Chicago Bulls',          wikipediaTitle: 'Chicago Bulls',          colors: ['#CE1141', '#000000'] },
  { id: 'nba-cavaliers',     sport: 'basketball', league: 'NBA', name: 'Cleveland Cavaliers',    wikipediaTitle: 'Cleveland Cavaliers',    colors: ['#860038', '#041E42', '#FDBB30'] },
  { id: 'nba-mavericks',     sport: 'basketball', league: 'NBA', name: 'Dallas Mavericks',       wikipediaTitle: 'Dallas Mavericks',       colors: ['#00538C', '#002B5E', '#B8C4CA'] },
  { id: 'nba-nuggets',       sport: 'basketball', league: 'NBA', name: 'Denver Nuggets',         wikipediaTitle: 'Denver Nuggets',         colors: ['#0E2240', '#FEC524', '#8B2131'] },
  { id: 'nba-pistons',       sport: 'basketball', league: 'NBA', name: 'Detroit Pistons',        wikipediaTitle: 'Detroit Pistons',        colors: ['#C8102E', '#1D42BA', '#002D62'] },
  { id: 'nba-warriors',      sport: 'basketball', league: 'NBA', name: 'Golden State Warriors',  wikipediaTitle: 'Golden State Warriors',  colors: ['#1D428A', '#FFC72C'] },
  { id: 'nba-rockets',       sport: 'basketball', league: 'NBA', name: 'Houston Rockets',        wikipediaTitle: 'Houston Rockets',        colors: ['#CE1141', '#000000', '#C4CED4'] },
  { id: 'nba-pacers',        sport: 'basketball', league: 'NBA', name: 'Indiana Pacers',         wikipediaTitle: 'Indiana Pacers',         colors: ['#002D62', '#FDBB30'] },
  { id: 'nba-clippers',      sport: 'basketball', league: 'NBA', name: 'LA Clippers',            wikipediaTitle: 'Los Angeles Clippers',   colors: ['#C8102E', '#1D428A', '#BEC0C2'] },
  { id: 'nba-lakers',        sport: 'basketball', league: 'NBA', name: 'Los Angeles Lakers',     wikipediaTitle: 'Los Angeles Lakers',     colors: ['#552583', '#FDB927'] },
  { id: 'nba-grizzlies',     sport: 'basketball', league: 'NBA', name: 'Memphis Grizzlies',      wikipediaTitle: 'Memphis Grizzlies',      colors: ['#5D76A9', '#12173F', '#F5B112'] },
  { id: 'nba-heat',          sport: 'basketball', league: 'NBA', name: 'Miami Heat',             wikipediaTitle: 'Miami Heat',             colors: ['#98002E', '#F9A01B', '#000000'] },
  { id: 'nba-bucks',         sport: 'basketball', league: 'NBA', name: 'Milwaukee Bucks',        wikipediaTitle: 'Milwaukee Bucks',        colors: ['#00471B', '#EEE1C6', '#0077C0'] },
  { id: 'nba-timberwolves',  sport: 'basketball', league: 'NBA', name: 'Minnesota Timberwolves', wikipediaTitle: 'Minnesota Timberwolves', colors: ['#0C2340', '#236192', '#9EA2A2'] },
  { id: 'nba-pelicans',      sport: 'basketball', league: 'NBA', name: 'New Orleans Pelicans',   wikipediaTitle: 'New Orleans Pelicans',   colors: ['#0C2340', '#C8102E', '#85714D'] },
  { id: 'nba-knicks',        sport: 'basketball', league: 'NBA', name: 'New York Knicks',        wikipediaTitle: 'New York Knicks',        colors: ['#006BB6', '#F58426', '#BEC0C2'] },
  { id: 'nba-thunder',       sport: 'basketball', league: 'NBA', name: 'Oklahoma City Thunder',  wikipediaTitle: 'Oklahoma City Thunder',  colors: ['#007AC1', '#EF3B24', '#002D62'] },
  { id: 'nba-magic',         sport: 'basketball', league: 'NBA', name: 'Orlando Magic',          wikipediaTitle: 'Orlando Magic',          colors: ['#0077C0', '#C4CED4', '#000000'] },
  { id: 'nba-76ers',         sport: 'basketball', league: 'NBA', name: 'Philadelphia 76ers',     wikipediaTitle: 'Philadelphia 76ers',     colors: ['#006BB6', '#ED174C', '#002B5C'] },
  { id: 'nba-suns',          sport: 'basketball', league: 'NBA', name: 'Phoenix Suns',           wikipediaTitle: 'Phoenix Suns',           colors: ['#1D1160', '#E56020', '#000000'] },
  { id: 'nba-blazers',       sport: 'basketball', league: 'NBA', name: 'Portland Trail Blazers', wikipediaTitle: 'Portland Trail Blazers', colors: ['#E03A3E', '#000000'] },
  { id: 'nba-kings',         sport: 'basketball', league: 'NBA', name: 'Sacramento Kings',       wikipediaTitle: 'Sacramento Kings',       colors: ['#5A2D81', '#63727A', '#000000'] },
  { id: 'nba-spurs',         sport: 'basketball', league: 'NBA', name: 'San Antonio Spurs',      wikipediaTitle: 'San Antonio Spurs',      colors: ['#000000', '#C4CED4'] },
  { id: 'nba-raptors',       sport: 'basketball', league: 'NBA', name: 'Toronto Raptors',        wikipediaTitle: 'Toronto Raptors',        colors: ['#CE1141', '#000000', '#A1A1A4'] },
  { id: 'nba-jazz',          sport: 'basketball', league: 'NBA', name: 'Utah Jazz',              wikipediaTitle: 'Utah Jazz',              colors: ['#002B5C', '#F9A01B', '#00471B'] },
  { id: 'nba-wizards',       sport: 'basketball', league: 'NBA', name: 'Washington Wizards',     wikipediaTitle: 'Washington Wizards',     colors: ['#002B5C', '#E31837', '#C4CED4'] },

  // ============ MLB ============
  { id: 'mlb-diamondbacks', sport: 'baseball', league: 'MLB', name: 'Arizona Diamondbacks', wikipediaTitle: 'Arizona Diamondbacks', colors: ['#A71930', '#000000', '#E3D4AD'] },
  { id: 'mlb-braves',       sport: 'baseball', league: 'MLB', name: 'Atlanta Braves',       wikipediaTitle: 'Atlanta Braves',       colors: ['#13274F', '#CE1141'] },
  { id: 'mlb-orioles',      sport: 'baseball', league: 'MLB', name: 'Baltimore Orioles',    wikipediaTitle: 'Baltimore Orioles',    colors: ['#DF4601', '#000000'] },
  { id: 'mlb-redsox',       sport: 'baseball', league: 'MLB', name: 'Boston Red Sox',       wikipediaTitle: 'Boston Red Sox',       colors: ['#BD3039', '#0C2340'] },
  { id: 'mlb-cubs',         sport: 'baseball', league: 'MLB', name: 'Chicago Cubs',         wikipediaTitle: 'Chicago Cubs',         colors: ['#0E3386', '#CC3433'] },
  { id: 'mlb-whitesox',     sport: 'baseball', league: 'MLB', name: 'Chicago White Sox',    wikipediaTitle: 'Chicago White Sox',    colors: ['#27251F', '#C4CED4'] },
  { id: 'mlb-reds',         sport: 'baseball', league: 'MLB', name: 'Cincinnati Reds',      wikipediaTitle: 'Cincinnati Reds',      colors: ['#C6011F', '#000000'] },
  { id: 'mlb-guardians',    sport: 'baseball', league: 'MLB', name: 'Cleveland Guardians',  wikipediaTitle: 'Cleveland Guardians',  colors: ['#E31937', '#0C2340'] },
  { id: 'mlb-rockies',      sport: 'baseball', league: 'MLB', name: 'Colorado Rockies',     wikipediaTitle: 'Colorado Rockies',     colors: ['#333366', '#131413', '#C4CED4'] },
  { id: 'mlb-tigers',       sport: 'baseball', league: 'MLB', name: 'Detroit Tigers',       wikipediaTitle: 'Detroit Tigers',       colors: ['#0C2340', '#FA4616'] },
  { id: 'mlb-astros',       sport: 'baseball', league: 'MLB', name: 'Houston Astros',       wikipediaTitle: 'Houston Astros',       colors: ['#002D62', '#EB6E1F'] },
  { id: 'mlb-royals',       sport: 'baseball', league: 'MLB', name: 'Kansas City Royals',   wikipediaTitle: 'Kansas City Royals',   colors: ['#004687', '#BD9B60'] },
  { id: 'mlb-angels',       sport: 'baseball', league: 'MLB', name: 'Los Angeles Angels',   wikipediaTitle: 'Los Angeles Angels',   colors: ['#BA0021', '#003263', '#C4CED4'] },
  { id: 'mlb-dodgers',      sport: 'baseball', league: 'MLB', name: 'Los Angeles Dodgers',  wikipediaTitle: 'Los Angeles Dodgers',  colors: ['#005A9C', '#A5ACAF'] },
  { id: 'mlb-marlins',      sport: 'baseball', league: 'MLB', name: 'Miami Marlins',        wikipediaTitle: 'Miami Marlins',        colors: ['#00A3E0', '#EF3340', '#000000'] },
  { id: 'mlb-brewers',      sport: 'baseball', league: 'MLB', name: 'Milwaukee Brewers',    wikipediaTitle: 'Milwaukee Brewers',    colors: ['#12284B', '#FFC52F'] },
  { id: 'mlb-twins',        sport: 'baseball', league: 'MLB', name: 'Minnesota Twins',      wikipediaTitle: 'Minnesota Twins',      colors: ['#002B5C', '#D31145'] },
  { id: 'mlb-mets',         sport: 'baseball', league: 'MLB', name: 'New York Mets',        wikipediaTitle: 'New York Mets',        colors: ['#002D72', '#FF5910'] },
  { id: 'mlb-yankees',      sport: 'baseball', league: 'MLB', name: 'New York Yankees',     wikipediaTitle: 'New York Yankees',     colors: ['#0C2340', '#FFFFFF'] },
  { id: 'mlb-athletics',    sport: 'baseball', league: 'MLB', name: 'Athletics',            wikipediaTitle: 'Athletics (baseball)', colors: ['#003831', '#EFB21E'] },
  { id: 'mlb-phillies',     sport: 'baseball', league: 'MLB', name: 'Philadelphia Phillies', wikipediaTitle: 'Philadelphia Phillies', colors: ['#E81828', '#002D72'] },
  { id: 'mlb-pirates',      sport: 'baseball', league: 'MLB', name: 'Pittsburgh Pirates',   wikipediaTitle: 'Pittsburgh Pirates',   colors: ['#27251F', '#FDB827'] },
  { id: 'mlb-padres',       sport: 'baseball', league: 'MLB', name: 'San Diego Padres',     wikipediaTitle: 'San Diego Padres',     colors: ['#2F241D', '#FFC425'] },
  { id: 'mlb-giants',       sport: 'baseball', league: 'MLB', name: 'San Francisco Giants', wikipediaTitle: 'San Francisco Giants', colors: ['#FD5A1E', '#27251F', '#AE8F6F'] },
  { id: 'mlb-mariners',     sport: 'baseball', league: 'MLB', name: 'Seattle Mariners',     wikipediaTitle: 'Seattle Mariners',     colors: ['#0C2C56', '#005C5C', '#C4CED4'] },
  { id: 'mlb-cardinals',    sport: 'baseball', league: 'MLB', name: 'St. Louis Cardinals',  wikipediaTitle: 'St. Louis Cardinals',  colors: ['#C41E3A', '#0C2340', '#FEDB00'] },
  { id: 'mlb-rays',         sport: 'baseball', league: 'MLB', name: 'Tampa Bay Rays',       wikipediaTitle: 'Tampa Bay Rays',       colors: ['#092C5C', '#8FBCE6', '#F5D130'] },
  { id: 'mlb-rangers',      sport: 'baseball', league: 'MLB', name: 'Texas Rangers',        wikipediaTitle: 'Texas Rangers (baseball)', colors: ['#003278', '#C0111F'] },
  { id: 'mlb-bluejays',     sport: 'baseball', league: 'MLB', name: 'Toronto Blue Jays',    wikipediaTitle: 'Toronto Blue Jays',    colors: ['#134A8E', '#1D2D5C', '#E8291C'] },
  { id: 'mlb-nationals',    sport: 'baseball', league: 'MLB', name: 'Washington Nationals', wikipediaTitle: 'Washington Nationals', colors: ['#AB0003', '#14225A'] },

  // ============ NHL ============
  { id: 'nhl-ducks',          sport: 'ice-hockey', league: 'NHL', name: 'Anaheim Ducks',          wikipediaTitle: 'Anaheim Ducks',          colors: ['#F47A38', '#B9975B', '#000000'] },
  { id: 'nhl-bruins',         sport: 'ice-hockey', league: 'NHL', name: 'Boston Bruins',          wikipediaTitle: 'Boston Bruins',          colors: ['#FFB81C', '#000000'] },
  { id: 'nhl-sabres',         sport: 'ice-hockey', league: 'NHL', name: 'Buffalo Sabres',         wikipediaTitle: 'Buffalo Sabres',         colors: ['#002654', '#FCB514'] },
  { id: 'nhl-flames',         sport: 'ice-hockey', league: 'NHL', name: 'Calgary Flames',         wikipediaTitle: 'Calgary Flames',         colors: ['#C8102E', '#F1BE48', '#111111'] },
  { id: 'nhl-hurricanes',     sport: 'ice-hockey', league: 'NHL', name: 'Carolina Hurricanes',    wikipediaTitle: 'Carolina Hurricanes',    colors: ['#CC0000', '#000000', '#A2AAAD'] },
  { id: 'nhl-blackhawks',     sport: 'ice-hockey', league: 'NHL', name: 'Chicago Blackhawks',     wikipediaTitle: 'Chicago Blackhawks',     colors: ['#CF0A2C', '#000000'] },
  { id: 'nhl-avalanche',      sport: 'ice-hockey', league: 'NHL', name: 'Colorado Avalanche',     wikipediaTitle: 'Colorado Avalanche',     colors: ['#6F263D', '#236192', '#A2AAAD'] },
  { id: 'nhl-bluejackets',    sport: 'ice-hockey', league: 'NHL', name: 'Columbus Blue Jackets',  wikipediaTitle: 'Columbus Blue Jackets',  colors: ['#002654', '#CE1126', '#A4A9AD'] },
  { id: 'nhl-stars',          sport: 'ice-hockey', league: 'NHL', name: 'Dallas Stars',           wikipediaTitle: 'Dallas Stars',           colors: ['#006847', '#000000', '#8F8F8C'] },
  { id: 'nhl-redwings',       sport: 'ice-hockey', league: 'NHL', name: 'Detroit Red Wings',      wikipediaTitle: 'Detroit Red Wings',      colors: ['#CE1126', '#FFFFFF'] },
  { id: 'nhl-oilers',         sport: 'ice-hockey', league: 'NHL', name: 'Edmonton Oilers',        wikipediaTitle: 'Edmonton Oilers',        colors: ['#FF4C00', '#041E42'] },
  { id: 'nhl-panthers',       sport: 'ice-hockey', league: 'NHL', name: 'Florida Panthers',       wikipediaTitle: 'Florida Panthers',       colors: ['#C8102E', '#041E42', '#B9975B'] },
  { id: 'nhl-kings',          sport: 'ice-hockey', league: 'NHL', name: 'Los Angeles Kings',      wikipediaTitle: 'Los Angeles Kings',      colors: ['#111111', '#A2AAAD'] },
  { id: 'nhl-wild',           sport: 'ice-hockey', league: 'NHL', name: 'Minnesota Wild',         wikipediaTitle: 'Minnesota Wild',         colors: ['#154734', '#A6192E', '#EAAA00'] },
  { id: 'nhl-canadiens',      sport: 'ice-hockey', league: 'NHL', name: 'Montreal Canadiens',     wikipediaTitle: 'Montreal Canadiens',     colors: ['#AF1E2D', '#192168'] },
  { id: 'nhl-predators',      sport: 'ice-hockey', league: 'NHL', name: 'Nashville Predators',    wikipediaTitle: 'Nashville Predators',    colors: ['#FFB81C', '#041E42'] },
  { id: 'nhl-devils',         sport: 'ice-hockey', league: 'NHL', name: 'New Jersey Devils',      wikipediaTitle: 'New Jersey Devils',      colors: ['#CE1126', '#000000'] },
  { id: 'nhl-islanders',      sport: 'ice-hockey', league: 'NHL', name: 'New York Islanders',     wikipediaTitle: 'New York Islanders',     colors: ['#F47D30', '#00539B'] },
  { id: 'nhl-rangers',        sport: 'ice-hockey', league: 'NHL', name: 'New York Rangers',       wikipediaTitle: 'New York Rangers',       colors: ['#0038A8', '#CE1126'] },
  { id: 'nhl-senators',       sport: 'ice-hockey', league: 'NHL', name: 'Ottawa Senators',        wikipediaTitle: 'Ottawa Senators',        colors: ['#C8102E', '#000000', '#C2912C'] },
  { id: 'nhl-flyers',         sport: 'ice-hockey', league: 'NHL', name: 'Philadelphia Flyers',    wikipediaTitle: 'Philadelphia Flyers',    colors: ['#F74902', '#000000'] },
  { id: 'nhl-penguins',       sport: 'ice-hockey', league: 'NHL', name: 'Pittsburgh Penguins',    wikipediaTitle: 'Pittsburgh Penguins',    colors: ['#000000', '#CFC493', '#FCB514'] },
  { id: 'nhl-sharks',         sport: 'ice-hockey', league: 'NHL', name: 'San Jose Sharks',        wikipediaTitle: 'San Jose Sharks',        colors: ['#006D75', '#E57200', '#000000'] },
  { id: 'nhl-kraken',         sport: 'ice-hockey', league: 'NHL', name: 'Seattle Kraken',         wikipediaTitle: 'Seattle Kraken',         colors: ['#001628', '#99D9D9', '#355464', '#E9072B'] },
  { id: 'nhl-blues',          sport: 'ice-hockey', league: 'NHL', name: 'St. Louis Blues',        wikipediaTitle: 'St. Louis Blues',        colors: ['#002F87', '#FCB514', '#041E42'] },
  { id: 'nhl-lightning',      sport: 'ice-hockey', league: 'NHL', name: 'Tampa Bay Lightning',    wikipediaTitle: 'Tampa Bay Lightning',    colors: ['#002868', '#FFFFFF'] },
  { id: 'nhl-mapleleafs',     sport: 'ice-hockey', league: 'NHL', name: 'Toronto Maple Leafs',    wikipediaTitle: 'Toronto Maple Leafs',    colors: ['#00205B', '#FFFFFF'] },
  { id: 'nhl-mammoth',        sport: 'ice-hockey', league: 'NHL', name: 'Utah Mammoth',           wikipediaTitle: 'Utah Mammoth',           colors: ['#00205B', '#71AFE5', '#000000'] },
  { id: 'nhl-canucks',        sport: 'ice-hockey', league: 'NHL', name: 'Vancouver Canucks',      wikipediaTitle: 'Vancouver Canucks',      colors: ['#00205B', '#008852', '#97999B'] },
  { id: 'nhl-goldenknights',  sport: 'ice-hockey', league: 'NHL', name: 'Vegas Golden Knights',   wikipediaTitle: 'Vegas Golden Knights',   colors: ['#B4975A', '#333F42', '#C8102E'] },
  { id: 'nhl-capitals',       sport: 'ice-hockey', league: 'NHL', name: 'Washington Capitals',    wikipediaTitle: 'Washington Capitals',    colors: ['#C8102E', '#041E42', '#FFFFFF'] },
  { id: 'nhl-jets',           sport: 'ice-hockey', league: 'NHL', name: 'Winnipeg Jets',          wikipediaTitle: 'Winnipeg Jets',          colors: ['#041E42', '#C8102E', '#A2AAAD'] },

  // ============ Premier League ============
  { id: 'pl-arsenal',         sport: 'football', league: 'Premier League', name: 'Arsenal',              wikipediaTitle: 'Arsenal F.C.',                 colors: ['#EF0107', '#023474', '#9C824A'] },
  { id: 'pl-astonvilla',      sport: 'football', league: 'Premier League', name: 'Aston Villa',          wikipediaTitle: 'Aston Villa F.C.',             colors: ['#670E36', '#95BFE5'] },
  { id: 'pl-bournemouth',     sport: 'football', league: 'Premier League', name: 'Bournemouth',          wikipediaTitle: 'A.F.C. Bournemouth',           colors: ['#DA291C', '#000000'] },
  { id: 'pl-brentford',       sport: 'football', league: 'Premier League', name: 'Brentford',            wikipediaTitle: 'Brentford F.C.',               colors: ['#E30613', '#FFFFFF'] },
  { id: 'pl-brighton',        sport: 'football', league: 'Premier League', name: 'Brighton & Hove Albion', wikipediaTitle: 'Brighton & Hove Albion F.C.', colors: ['#0057B8', '#FFFFFF'] },
  { id: 'pl-burnley',         sport: 'football', league: 'Premier League', name: 'Burnley',              wikipediaTitle: 'Burnley F.C.',                 colors: ['#6C1D45', '#99D6EA'] },
  { id: 'pl-chelsea',         sport: 'football', league: 'Premier League', name: 'Chelsea',              wikipediaTitle: 'Chelsea F.C.',                 colors: ['#034694', '#FFFFFF'] },
  { id: 'pl-crystalpalace',   sport: 'football', league: 'Premier League', name: 'Crystal Palace',       wikipediaTitle: 'Crystal Palace F.C.',          colors: ['#1B458F', '#C4122E'] },
  { id: 'pl-everton',         sport: 'football', league: 'Premier League', name: 'Everton',              wikipediaTitle: 'Everton F.C.',                 colors: ['#003399', '#FFFFFF'] },
  { id: 'pl-fulham',          sport: 'football', league: 'Premier League', name: 'Fulham',               wikipediaTitle: 'Fulham F.C.',                  colors: ['#FFFFFF', '#000000', '#CC0000'] },
  { id: 'pl-leeds',           sport: 'football', league: 'Premier League', name: 'Leeds United',         wikipediaTitle: 'Leeds United F.C.',            colors: ['#FFFFFF', '#1D428A', '#FFCD00'] },
  { id: 'pl-liverpool',       sport: 'football', league: 'Premier League', name: 'Liverpool',            wikipediaTitle: 'Liverpool F.C.',               colors: ['#C8102E', '#00B2A9', '#F6EB61'] },
  { id: 'pl-mancity',         sport: 'football', league: 'Premier League', name: 'Manchester City',      wikipediaTitle: 'Manchester City F.C.',         colors: ['#6CABDD', '#1C2C5B', '#FFC659'] },
  { id: 'pl-manunited',       sport: 'football', league: 'Premier League', name: 'Manchester United',    wikipediaTitle: 'Manchester United F.C.',       colors: ['#DA291C', '#FBE122', '#000000'] },
  { id: 'pl-newcastle',       sport: 'football', league: 'Premier League', name: 'Newcastle United',     wikipediaTitle: 'Newcastle United F.C.',        colors: ['#241F20', '#FFFFFF'] },
  { id: 'pl-nottsforest',     sport: 'football', league: 'Premier League', name: 'Nottingham Forest',    wikipediaTitle: 'Nottingham Forest F.C.',       colors: ['#DD0000', '#FFFFFF'] },
  { id: 'pl-sunderland',      sport: 'football', league: 'Premier League', name: 'Sunderland',           wikipediaTitle: 'Sunderland A.F.C.',             colors: ['#EB172B', '#FFFFFF', '#000000'] },
  { id: 'pl-tottenham',       sport: 'football', league: 'Premier League', name: 'Tottenham Hotspur',    wikipediaTitle: 'Tottenham Hotspur F.C.',       colors: ['#132257', '#FFFFFF'] },
  { id: 'pl-westham',         sport: 'football', league: 'Premier League', name: 'West Ham United',      wikipediaTitle: 'West Ham United F.C.',         colors: ['#7A263A', '#1BB1E7', '#F3D459'] },
  { id: 'pl-wolves',          sport: 'football', league: 'Premier League', name: 'Wolverhampton Wanderers', wikipediaTitle: 'Wolverhampton Wanderers F.C.', colors: ['#FDB913', '#231F20'] },

  // ============ La Liga ============
  { id: 'laliga-athletic',     sport: 'football', league: 'La Liga', name: 'Athletic Club',     wikipediaTitle: 'Athletic Bilbao',         colors: ['#EE2523', '#FFFFFF'] },
  { id: 'laliga-atletico',     sport: 'football', league: 'La Liga', name: 'Atlético Madrid',   wikipediaTitle: 'Atlético Madrid',         colors: ['#CB3524', '#FFFFFF', '#262E62'] },
  { id: 'laliga-barcelona',    sport: 'football', league: 'La Liga', name: 'Barcelona',         wikipediaTitle: 'FC Barcelona',            colors: ['#004D98', '#A50044', '#EDBB00'] },
  { id: 'laliga-celta',        sport: 'football', league: 'La Liga', name: 'Celta Vigo',        wikipediaTitle: 'RC Celta de Vigo',        colors: ['#8AC3EE', '#FFFFFF'] },
  { id: 'laliga-elche',        sport: 'football', league: 'La Liga', name: 'Elche',             wikipediaTitle: 'Elche CF',                colors: ['#FFFFFF', '#008C45'] },
  { id: 'laliga-espanyol',     sport: 'football', league: 'La Liga', name: 'Espanyol',          wikipediaTitle: 'RCD Espanyol',            colors: ['#004B9D', '#FFFFFF'] },
  { id: 'laliga-getafe',       sport: 'football', league: 'La Liga', name: 'Getafe',            wikipediaTitle: 'Getafe CF',               colors: ['#003DA5', '#FFFFFF'] },
  { id: 'laliga-girona',       sport: 'football', league: 'La Liga', name: 'Girona',            wikipediaTitle: 'Girona FC',               colors: ['#CD2129', '#FFFFFF'] },
  { id: 'laliga-laspalmas',    sport: 'football', league: 'La Liga', name: 'Las Palmas',        wikipediaTitle: 'UD Las Palmas',           colors: ['#FFE500', '#004B9D'] },
  { id: 'laliga-leganes',      sport: 'football', league: 'La Liga', name: 'Leganés',           wikipediaTitle: 'CD Leganés',              colors: ['#004D98', '#FFFFFF'] },
  { id: 'laliga-levante',      sport: 'football', league: 'La Liga', name: 'Levante',           wikipediaTitle: 'Levante UD',              colors: ['#003580', '#DA291C', '#FFFFFF'] },
  { id: 'laliga-mallorca',     sport: 'football', league: 'La Liga', name: 'Mallorca',          wikipediaTitle: 'RCD Mallorca',            colors: ['#CC2027', '#FFCD00'] },
  { id: 'laliga-osasuna',      sport: 'football', league: 'La Liga', name: 'Osasuna',           wikipediaTitle: 'CA Osasuna',              colors: ['#DA291C', '#001F5B'] },
  { id: 'laliga-rayo',         sport: 'football', league: 'La Liga', name: 'Rayo Vallecano',    wikipediaTitle: 'Rayo Vallecano',          colors: ['#E32219', '#FFFFFF'] },
  { id: 'laliga-betis',        sport: 'football', league: 'La Liga', name: 'Real Betis',        wikipediaTitle: 'Real Betis',              colors: ['#00954C', '#FFFFFF'] },
  { id: 'laliga-madrid',       sport: 'football', league: 'La Liga', name: 'Real Madrid',       wikipediaTitle: 'Real Madrid CF',          colors: ['#FFFFFF', '#FEBE10', '#00529F'] },
  { id: 'laliga-oviedo',       sport: 'football', league: 'La Liga', name: 'Real Oviedo',       wikipediaTitle: 'Real Oviedo',             colors: ['#003DA5', '#FFFFFF'] },
  { id: 'laliga-sociedad',     sport: 'football', league: 'La Liga', name: 'Real Sociedad',     wikipediaTitle: 'Real Sociedad',           colors: ['#003DA5', '#FFFFFF'] },
  { id: 'laliga-sevilla',      sport: 'football', league: 'La Liga', name: 'Sevilla',           wikipediaTitle: 'Sevilla FC',              colors: ['#D00027', '#FFFFFF'] },
  { id: 'laliga-valencia',     sport: 'football', league: 'La Liga', name: 'Valencia',          wikipediaTitle: 'Valencia CF',             colors: ['#FF6600', '#FFFFFF', '#000000'] },
  { id: 'laliga-villarreal',   sport: 'football', league: 'La Liga', name: 'Villarreal',        wikipediaTitle: 'Villarreal CF',           colors: ['#FFE500', '#005CB9'] },

  // ============ Serie A ============
  { id: 'seriea-atalanta',    sport: 'football', league: 'Serie A', name: 'Atalanta',       wikipediaTitle: 'Atalanta B.C.',           colors: ['#1B65B3', '#000000'] },
  { id: 'seriea-bologna',     sport: 'football', league: 'Serie A', name: 'Bologna',        wikipediaTitle: 'Bologna F.C. 1909',       colors: ['#911B2C', '#001A45'] },
  { id: 'seriea-cagliari',    sport: 'football', league: 'Serie A', name: 'Cagliari',       wikipediaTitle: 'Cagliari Calcio',         colors: ['#B40425', '#002759'] },
  { id: 'seriea-como',        sport: 'football', league: 'Serie A', name: 'Como',           wikipediaTitle: 'Como 1907',               colors: ['#003C8C', '#FFFFFF'] },
  { id: 'seriea-cremonese',   sport: 'football', league: 'Serie A', name: 'Cremonese',      wikipediaTitle: 'U.S. Cremonese',          colors: ['#A41C2F', '#FFFFFF', '#808080'] },
  { id: 'seriea-fiorentina',  sport: 'football', league: 'Serie A', name: 'Fiorentina',     wikipediaTitle: 'ACF Fiorentina',          colors: ['#432C7B', '#FFFFFF'] },
  { id: 'seriea-genoa',       sport: 'football', league: 'Serie A', name: 'Genoa',          wikipediaTitle: 'Genoa CFC',               colors: ['#C8102E', '#002F6C'] },
  { id: 'seriea-verona',      sport: 'football', league: 'Serie A', name: 'Hellas Verona',  wikipediaTitle: 'Hellas Verona F.C.',      colors: ['#FFC72C', '#002F6C'] },
  { id: 'seriea-inter',       sport: 'football', league: 'Serie A', name: 'Inter Milan',    wikipediaTitle: 'Inter Milan',             colors: ['#1F2D58', '#000000'] },
  { id: 'seriea-juventus',    sport: 'football', league: 'Serie A', name: 'Juventus',       wikipediaTitle: 'Juventus F.C.',           colors: ['#000000', '#FFFFFF'] },
  { id: 'seriea-lazio',       sport: 'football', league: 'Serie A', name: 'Lazio',          wikipediaTitle: 'S.S. Lazio',              colors: ['#87D8F7', '#FFFFFF'] },
  { id: 'seriea-lecce',       sport: 'football', league: 'Serie A', name: 'Lecce',          wikipediaTitle: 'U.S. Lecce',              colors: ['#FFD400', '#DA291C'] },
  { id: 'seriea-milan',       sport: 'football', league: 'Serie A', name: 'AC Milan',       wikipediaTitle: 'A.C. Milan',              colors: ['#FB090B', '#000000'] },
  { id: 'seriea-napoli',      sport: 'football', league: 'Serie A', name: 'Napoli',         wikipediaTitle: 'S.S.C. Napoli',           colors: ['#12A0D7', '#FFFFFF'] },
  { id: 'seriea-parma',       sport: 'football', league: 'Serie A', name: 'Parma',          wikipediaTitle: 'Parma Calcio 1913',       colors: ['#FFE500', '#003DA5'] },
  { id: 'seriea-pisa',        sport: 'football', league: 'Serie A', name: 'Pisa',           wikipediaTitle: 'Pisa S.C.',               colors: ['#000000', '#1F2D58'] },
  { id: 'seriea-roma',        sport: 'football', league: 'Serie A', name: 'Roma',           wikipediaTitle: 'A.S. Roma',               colors: ['#8E1F2F', '#FFB81C'] },
  { id: 'seriea-sassuolo',    sport: 'football', league: 'Serie A', name: 'Sassuolo',       wikipediaTitle: 'U.S. Sassuolo Calcio',    colors: ['#009638', '#000000'] },
  { id: 'seriea-torino',      sport: 'football', league: 'Serie A', name: 'Torino',         wikipediaTitle: 'Torino F.C.',             colors: ['#8B1F2F', '#FFFFFF'] },
  { id: 'seriea-udinese',     sport: 'football', league: 'Serie A', name: 'Udinese',        wikipediaTitle: 'Udinese Calcio',          colors: ['#000000', '#FFFFFF'] },

  // ============ Bundesliga ============
  { id: 'bun-augsburg',       sport: 'football', league: 'Bundesliga', name: 'Augsburg',                   wikipediaTitle: 'FC Augsburg',                  colors: ['#BA3733', '#007A33', '#FFFFFF'] },
  { id: 'bun-leverkusen',     sport: 'football', league: 'Bundesliga', name: 'Bayer Leverkusen',           wikipediaTitle: 'Bayer 04 Leverkusen',          colors: ['#E32221', '#000000'] },
  { id: 'bun-bayern',         sport: 'football', league: 'Bundesliga', name: 'Bayern Munich',              wikipediaTitle: 'FC Bayern Munich',             colors: ['#DC052D', '#0066B2', '#FFFFFF'] },
  { id: 'bun-dortmund',       sport: 'football', league: 'Bundesliga', name: 'Borussia Dortmund',          wikipediaTitle: 'Borussia Dortmund',            colors: ['#FDE100', '#000000'] },
  { id: 'bun-gladbach',       sport: 'football', league: 'Bundesliga', name: 'Borussia Mönchengladbach',   wikipediaTitle: 'Borussia Mönchengladbach',     colors: ['#00B04F', '#FFFFFF', '#000000'] },
  { id: 'bun-frankfurt',      sport: 'football', league: 'Bundesliga', name: 'Eintracht Frankfurt',        wikipediaTitle: 'Eintracht Frankfurt',          colors: ['#E1000F', '#000000'] },
  { id: 'bun-freiburg',       sport: 'football', league: 'Bundesliga', name: 'SC Freiburg',                wikipediaTitle: 'SC Freiburg',                  colors: ['#CC0000', '#000000', '#FFFFFF'] },
  { id: 'bun-hamburg',        sport: 'football', league: 'Bundesliga', name: 'Hamburger SV',               wikipediaTitle: 'Hamburger SV',                 colors: ['#003DA5', '#000000', '#FFFFFF'] },
  { id: 'bun-heidenheim',     sport: 'football', league: 'Bundesliga', name: '1. FC Heidenheim',           wikipediaTitle: '1. FC Heidenheim',             colors: ['#D40026', '#003DA5', '#FFFFFF'] },
  { id: 'bun-hoffenheim',     sport: 'football', league: 'Bundesliga', name: 'TSG Hoffenheim',             wikipediaTitle: 'TSG 1899 Hoffenheim',          colors: ['#1961AC', '#FFFFFF'] },
  { id: 'bun-koln',           sport: 'football', league: 'Bundesliga', name: '1. FC Köln',                 wikipediaTitle: '1. FC Köln',                   colors: ['#E2001A', '#FFFFFF'] },
  { id: 'bun-mainz',          sport: 'football', league: 'Bundesliga', name: 'Mainz 05',                   wikipediaTitle: '1. FSV Mainz 05',              colors: ['#C8102E', '#FFFFFF'] },
  { id: 'bun-leipzig',        sport: 'football', league: 'Bundesliga', name: 'RB Leipzig',                 wikipediaTitle: 'RB Leipzig',                   colors: ['#DD0741', '#FFFFFF', '#FFCD00'] },
  { id: 'bun-stpauli',        sport: 'football', league: 'Bundesliga', name: 'St. Pauli',                  wikipediaTitle: 'FC St. Pauli',                 colors: ['#5A341C', '#D71920', '#FFFFFF'] },
  { id: 'bun-stuttgart',      sport: 'football', league: 'Bundesliga', name: 'VfB Stuttgart',              wikipediaTitle: 'VfB Stuttgart',                colors: ['#E32219', '#FFFFFF'] },
  { id: 'bun-union',          sport: 'football', league: 'Bundesliga', name: 'Union Berlin',               wikipediaTitle: '1. FC Union Berlin',           colors: ['#EB1923', '#FFD200', '#FFFFFF'] },
  { id: 'bun-werder',         sport: 'football', league: 'Bundesliga', name: 'Werder Bremen',              wikipediaTitle: 'SV Werder Bremen',             colors: ['#1D9053', '#FFFFFF'] },
  { id: 'bun-wolfsburg',      sport: 'football', league: 'Bundesliga', name: 'VfL Wolfsburg',              wikipediaTitle: 'VfL Wolfsburg',                colors: ['#65B32E', '#FFFFFF'] },

  // ============ Ligue 1 ============
  { id: 'l1-angers',          sport: 'football', league: 'Ligue 1', name: 'Angers SCO',          wikipediaTitle: 'Angers SCO',                       colors: ['#000000', '#FFFFFF'] },
  { id: 'l1-auxerre',         sport: 'football', league: 'Ligue 1', name: 'AJ Auxerre',          wikipediaTitle: 'AJ Auxerre',                       colors: ['#FFFFFF', '#142A50'] },
  { id: 'l1-brest',           sport: 'football', league: 'Ligue 1', name: 'Stade Brestois',      wikipediaTitle: 'Stade Brestois 29',                colors: ['#C8102E', '#FFFFFF'] },
  { id: 'l1-lehavre',         sport: 'football', league: 'Ligue 1', name: 'Le Havre',            wikipediaTitle: 'Le Havre AC',                      colors: ['#6CACE4', '#001F5B'] },
  { id: 'l1-lens',            sport: 'football', league: 'Ligue 1', name: 'RC Lens',             wikipediaTitle: 'RC Lens',                          colors: ['#DA291C', '#FFCD00'] },
  { id: 'l1-lille',           sport: 'football', league: 'Ligue 1', name: 'Lille (LOSC)',        wikipediaTitle: 'Lille OSC',                        colors: ['#E20613', '#1F4287', '#FFFFFF'] },
  { id: 'l1-lorient',         sport: 'football', league: 'Ligue 1', name: 'FC Lorient',          wikipediaTitle: 'FC Lorient',                       colors: ['#F36C21', '#000000'] },
  { id: 'l1-lyon',            sport: 'football', league: 'Ligue 1', name: 'Olympique Lyonnais',  wikipediaTitle: 'Olympique Lyonnais',               colors: ['#003DA5', '#DA291C', '#FFFFFF'] },
  { id: 'l1-marseille',       sport: 'football', league: 'Ligue 1', name: 'Olympique de Marseille', wikipediaTitle: 'Olympique de Marseille',         colors: ['#2FAEE0', '#FFFFFF'] },
  { id: 'l1-metz',            sport: 'football', league: 'Ligue 1', name: 'FC Metz',             wikipediaTitle: 'FC Metz',                          colors: ['#861F41', '#FFFFFF'] },
  { id: 'l1-monaco',          sport: 'football', league: 'Ligue 1', name: 'AS Monaco',           wikipediaTitle: 'AS Monaco FC',                     colors: ['#ED1C24', '#FFFFFF'] },
  { id: 'l1-nantes',          sport: 'football', league: 'Ligue 1', name: 'FC Nantes',           wikipediaTitle: 'FC Nantes',                        colors: ['#FFD200', '#1D9053', '#FFFFFF'] },
  { id: 'l1-nice',            sport: 'football', league: 'Ligue 1', name: 'OGC Nice',            wikipediaTitle: 'OGC Nice',                         colors: ['#D71920', '#000000', '#FFFFFF'] },
  { id: 'l1-parisfc',         sport: 'football', league: 'Ligue 1', name: 'Paris FC',            wikipediaTitle: 'Paris FC',                         colors: ['#1A3E72', '#0072CE', '#FFFFFF'] },
  { id: 'l1-psg',             sport: 'football', league: 'Ligue 1', name: 'Paris Saint-Germain', wikipediaTitle: 'Paris Saint-Germain F.C.',          colors: ['#004170', '#DA291C', '#FFFFFF'] },
  { id: 'l1-rennes',          sport: 'football', league: 'Ligue 1', name: 'Stade Rennais',       wikipediaTitle: 'Stade Rennais F.C.',                colors: ['#DA291C', '#000000'] },
  { id: 'l1-strasbourg',      sport: 'football', league: 'Ligue 1', name: 'RC Strasbourg',       wikipediaTitle: 'RC Strasbourg Alsace',              colors: ['#003D7C', '#FFFFFF'] },
  { id: 'l1-toulouse',        sport: 'football', league: 'Ligue 1', name: 'Toulouse FC',         wikipediaTitle: 'Toulouse FC',                      colors: ['#5C2D8C', '#FFFFFF'] },
];
