// FBS college football teams for the 2025-26 season. Conference data is the
// post-2024-realignment landscape (Texas/Oklahoma in SEC, USC/UCLA/Oregon/
// Washington in Big Ten, Cal/Stanford/SMU in ACC, Arizona/ASU/Colorado/Utah
// in Big 12). Compiled in parallel by per-conference agents — see the
// workflow log if anything looks stale.

import type { SeedTeam } from './types.ts';

export const CFB_TEAMS: SeedTeam[] = [
  // ============ SEC ============
  { id: 'cfb-alabama',           sport: 'college-football', league: 'SEC', name: 'Alabama Crimson Tide',     wikipediaTitle: 'Alabama Crimson Tide football',     colors: ['#9E1B32', '#828A8F', '#FFFFFF'] },
  { id: 'cfb-arkansas',          sport: 'college-football', league: 'SEC', name: 'Arkansas Razorbacks',      wikipediaTitle: 'Arkansas Razorbacks football',      colors: ['#9D2235', '#FFFFFF'] },
  { id: 'cfb-auburn',            sport: 'college-football', league: 'SEC', name: 'Auburn Tigers',            wikipediaTitle: 'Auburn Tigers football',            colors: ['#0C2340', '#E87722'] },
  { id: 'cfb-florida',           sport: 'college-football', league: 'SEC', name: 'Florida Gators',           wikipediaTitle: 'Florida Gators football',           colors: ['#FA4616', '#0021A5'] },
  { id: 'cfb-georgia',           sport: 'college-football', league: 'SEC', name: 'Georgia Bulldogs',         wikipediaTitle: 'Georgia Bulldogs football',         colors: ['#BA0C2F', '#000000', '#FFFFFF'] },
  { id: 'cfb-kentucky',          sport: 'college-football', league: 'SEC', name: 'Kentucky Wildcats',        wikipediaTitle: 'Kentucky Wildcats football',        colors: ['#0033A0', '#FFFFFF', '#000000'] },
  { id: 'cfb-lsu',               sport: 'college-football', league: 'SEC', name: 'LSU Tigers',               wikipediaTitle: 'LSU Tigers football',               colors: ['#461D7C', '#FDD023'] },
  { id: 'cfb-mississippi-state', sport: 'college-football', league: 'SEC', name: 'Mississippi State Bulldogs', wikipediaTitle: 'Mississippi State Bulldogs football', colors: ['#660000', '#FFFFFF'] },
  { id: 'cfb-missouri',          sport: 'college-football', league: 'SEC', name: 'Missouri Tigers',          wikipediaTitle: 'Missouri Tigers football',          colors: ['#F1B82D', '#000000'] },
  { id: 'cfb-oklahoma',          sport: 'college-football', league: 'SEC', name: 'Oklahoma Sooners',         wikipediaTitle: 'Oklahoma Sooners football',         colors: ['#841617', '#FDF9D8'] },
  { id: 'cfb-ole-miss',          sport: 'college-football', league: 'SEC', name: 'Ole Miss Rebels',          wikipediaTitle: 'Ole Miss Rebels football',          colors: ['#CE1126', '#14213D'] },
  { id: 'cfb-south-carolina',    sport: 'college-football', league: 'SEC', name: 'South Carolina Gamecocks', wikipediaTitle: 'South Carolina Gamecocks football', colors: ['#73000A', '#000000'] },
  { id: 'cfb-tennessee',         sport: 'college-football', league: 'SEC', name: 'Tennessee Volunteers',     wikipediaTitle: 'Tennessee Volunteers football',     colors: ['#FF8200', '#FFFFFF', '#4B4B4B'] },
  { id: 'cfb-texas',             sport: 'college-football', league: 'SEC', name: 'Texas Longhorns',          wikipediaTitle: 'Texas Longhorns football',          colors: ['#BF5700', '#FFFFFF'] },
  { id: 'cfb-texas-am',          sport: 'college-football', league: 'SEC', name: 'Texas A&M Aggies',         wikipediaTitle: 'Texas A&M Aggies football',         colors: ['#500000', '#FFFFFF'] },
  { id: 'cfb-vanderbilt',        sport: 'college-football', league: 'SEC', name: 'Vanderbilt Commodores',    wikipediaTitle: 'Vanderbilt Commodores football',    colors: ['#000000', '#866D4B'] },

  // ============ Big Ten ============
  { id: 'cfb-illinois',          sport: 'college-football', league: 'Big Ten', name: 'Illinois Fighting Illini', wikipediaTitle: 'Illinois Fighting Illini football', colors: ['#FF5F05', '#13294B'] },
  { id: 'cfb-indiana',           sport: 'college-football', league: 'Big Ten', name: 'Indiana Hoosiers',        wikipediaTitle: 'Indiana Hoosiers football',        colors: ['#990000', '#EEEDEB'] },
  { id: 'cfb-iowa',              sport: 'college-football', league: 'Big Ten', name: 'Iowa Hawkeyes',           wikipediaTitle: 'Iowa Hawkeyes football',           colors: ['#000000', '#FFCD00'] },
  { id: 'cfb-maryland',          sport: 'college-football', league: 'Big Ten', name: 'Maryland Terrapins',      wikipediaTitle: 'Maryland Terrapins football',      colors: ['#E21833', '#FFD200', '#000000', '#FFFFFF'] },
  { id: 'cfb-michigan',          sport: 'college-football', league: 'Big Ten', name: 'Michigan Wolverines',     wikipediaTitle: 'Michigan Wolverines football',     colors: ['#00274C', '#FFCB05'] },
  { id: 'cfb-michigan-state',    sport: 'college-football', league: 'Big Ten', name: 'Michigan State Spartans', wikipediaTitle: 'Michigan State Spartans football', colors: ['#18453B', '#FFFFFF'] },
  { id: 'cfb-minnesota',         sport: 'college-football', league: 'Big Ten', name: 'Minnesota Golden Gophers', wikipediaTitle: 'Minnesota Golden Gophers football', colors: ['#7A0019', '#FFCC33'] },
  { id: 'cfb-nebraska',          sport: 'college-football', league: 'Big Ten', name: 'Nebraska Cornhuskers',    wikipediaTitle: 'Nebraska Cornhuskers football',    colors: ['#D00000', '#F5F1E7'] },
  { id: 'cfb-northwestern',      sport: 'college-football', league: 'Big Ten', name: 'Northwestern Wildcats',   wikipediaTitle: 'Northwestern Wildcats football',   colors: ['#4E2A84', '#FFFFFF'] },
  { id: 'cfb-ohio-state',        sport: 'college-football', league: 'Big Ten', name: 'Ohio State Buckeyes',     wikipediaTitle: 'Ohio State Buckeyes football',     colors: ['#BA0C2F', '#A7B1B7', '#FFFFFF'] },
  { id: 'cfb-oregon',            sport: 'college-football', league: 'Big Ten', name: 'Oregon Ducks',            wikipediaTitle: 'Oregon Ducks football',            colors: ['#154733', '#FEE123'] },
  { id: 'cfb-penn-state',        sport: 'college-football', league: 'Big Ten', name: 'Penn State Nittany Lions', wikipediaTitle: 'Penn State Nittany Lions football', colors: ['#001E44', '#FFFFFF'] },
  { id: 'cfb-purdue',            sport: 'college-football', league: 'Big Ten', name: 'Purdue Boilermakers',     wikipediaTitle: 'Purdue Boilermakers football',     colors: ['#CFB991', '#000000'] },
  { id: 'cfb-rutgers',           sport: 'college-football', league: 'Big Ten', name: 'Rutgers Scarlet Knights', wikipediaTitle: 'Rutgers Scarlet Knights football', colors: ['#CC0033', '#5F6A72', '#000000'] },
  { id: 'cfb-ucla',              sport: 'college-football', league: 'Big Ten', name: 'UCLA Bruins',             wikipediaTitle: 'UCLA Bruins football',             colors: ['#2774AE', '#FFD100', '#FFFFFF'] },
  { id: 'cfb-usc',               sport: 'college-football', league: 'Big Ten', name: 'USC Trojans',             wikipediaTitle: 'USC Trojans football',             colors: ['#990000', '#FFCC00'] },
  { id: 'cfb-washington',        sport: 'college-football', league: 'Big Ten', name: 'Washington Huskies',      wikipediaTitle: 'Washington Huskies football',      colors: ['#32006E', '#B7A57A'] },
  { id: 'cfb-wisconsin',         sport: 'college-football', league: 'Big Ten', name: 'Wisconsin Badgers',       wikipediaTitle: 'Wisconsin Badgers football',       colors: ['#C5050C', '#FFFFFF'] },

  // ============ ACC ============
  { id: 'cfb-boston-college',    sport: 'college-football', league: 'ACC', name: 'Boston College Eagles',      wikipediaTitle: 'Boston College Eagles football',      colors: ['#98002E', '#BC9B6A'] },
  { id: 'cfb-cal',               sport: 'college-football', league: 'ACC', name: 'California Golden Bears',    wikipediaTitle: 'California Golden Bears football',    colors: ['#003262', '#FDB515'] },
  { id: 'cfb-clemson',           sport: 'college-football', league: 'ACC', name: 'Clemson Tigers',             wikipediaTitle: 'Clemson Tigers football',             colors: ['#F56600', '#522D80'] },
  { id: 'cfb-duke',              sport: 'college-football', league: 'ACC', name: 'Duke Blue Devils',           wikipediaTitle: 'Duke Blue Devils football',           colors: ['#003087', '#FFFFFF'] },
  { id: 'cfb-florida-state',     sport: 'college-football', league: 'ACC', name: 'Florida State Seminoles',    wikipediaTitle: 'Florida State Seminoles football',    colors: ['#782F40', '#CEB888'] },
  { id: 'cfb-georgia-tech',      sport: 'college-football', league: 'ACC', name: 'Georgia Tech Yellow Jackets', wikipediaTitle: 'Georgia Tech Yellow Jackets football', colors: ['#B3A369', '#003057'] },
  { id: 'cfb-louisville',        sport: 'college-football', league: 'ACC', name: 'Louisville Cardinals',       wikipediaTitle: 'Louisville Cardinals football',       colors: ['#AD0000', '#000000'] },
  { id: 'cfb-miami-fl',          sport: 'college-football', league: 'ACC', name: 'Miami Hurricanes',           wikipediaTitle: 'Miami Hurricanes football',           colors: ['#F47321', '#005030'] },
  { id: 'cfb-nc-state',          sport: 'college-football', league: 'ACC', name: 'NC State Wolfpack',          wikipediaTitle: 'NC State Wolfpack football',          colors: ['#CC0000', '#000000', '#FFFFFF'] },
  { id: 'cfb-north-carolina',    sport: 'college-football', league: 'ACC', name: 'North Carolina Tar Heels',   wikipediaTitle: 'North Carolina Tar Heels football',   colors: ['#7BAFD4', '#13294B', '#FFFFFF'] },
  { id: 'cfb-pittsburgh',        sport: 'college-football', league: 'ACC', name: 'Pittsburgh Panthers',        wikipediaTitle: 'Pittsburgh Panthers football',        colors: ['#003594', '#FFB81C'] },
  { id: 'cfb-smu',               sport: 'college-football', league: 'ACC', name: 'SMU Mustangs',               wikipediaTitle: 'SMU Mustangs football',               colors: ['#0033A0', '#C8102E'] },
  { id: 'cfb-stanford',          sport: 'college-football', league: 'ACC', name: 'Stanford Cardinal',          wikipediaTitle: 'Stanford Cardinal football',          colors: ['#8C1515', '#4D4F53', '#2E2D29', '#FFFFFF'] },
  { id: 'cfb-syracuse',          sport: 'college-football', league: 'ACC', name: 'Syracuse Orange',            wikipediaTitle: 'Syracuse Orange football',            colors: ['#F76900', '#000E54', '#FFFFFF'] },
  { id: 'cfb-virginia',          sport: 'college-football', league: 'ACC', name: 'Virginia Cavaliers',         wikipediaTitle: 'Virginia Cavaliers football',         colors: ['#232D4B', '#F84C1E'] },
  { id: 'cfb-virginia-tech',     sport: 'college-football', league: 'ACC', name: 'Virginia Tech Hokies',       wikipediaTitle: 'Virginia Tech Hokies football',       colors: ['#630031', '#CF4420'] },
  { id: 'cfb-wake-forest',       sport: 'college-football', league: 'ACC', name: 'Wake Forest Demon Deacons',  wikipediaTitle: 'Wake Forest Demon Deacons football',  colors: ['#9E7E38', '#000000'] },

  // ============ Big 12 ============
  { id: 'cfb-arizona',           sport: 'college-football', league: 'Big 12', name: 'Arizona Wildcats',        wikipediaTitle: 'Arizona Wildcats football',        colors: ['#CC0033', '#003366'] },
  { id: 'cfb-arizona-state',     sport: 'college-football', league: 'Big 12', name: 'Arizona State Sun Devils', wikipediaTitle: 'Arizona State Sun Devils football', colors: ['#8C1D40', '#FFC627'] },
  { id: 'cfb-baylor',            sport: 'college-football', league: 'Big 12', name: 'Baylor Bears',            wikipediaTitle: 'Baylor Bears football',            colors: ['#154734', '#FFB81C'] },
  { id: 'cfb-byu',               sport: 'college-football', league: 'Big 12', name: 'BYU Cougars',             wikipediaTitle: 'BYU Cougars football',             colors: ['#002E5D', '#FFFFFF', '#0047BA'] },
  { id: 'cfb-cincinnati',        sport: 'college-football', league: 'Big 12', name: 'Cincinnati Bearcats',     wikipediaTitle: 'Cincinnati Bearcats football',     colors: ['#E00122', '#000000', '#FFFFFF'] },
  { id: 'cfb-colorado',          sport: 'college-football', league: 'Big 12', name: 'Colorado Buffaloes',      wikipediaTitle: 'Colorado Buffaloes football',      colors: ['#CFB87C', '#000000', '#A2A4A3'] },
  { id: 'cfb-houston',           sport: 'college-football', league: 'Big 12', name: 'Houston Cougars',         wikipediaTitle: 'Houston Cougars football',         colors: ['#C8102E', '#76232F', '#B2B4B2'] },
  { id: 'cfb-iowa-state',        sport: 'college-football', league: 'Big 12', name: 'Iowa State Cyclones',     wikipediaTitle: 'Iowa State Cyclones football',     colors: ['#C8102E', '#F1BE48'] },
  { id: 'cfb-kansas',            sport: 'college-football', league: 'Big 12', name: 'Kansas Jayhawks',         wikipediaTitle: 'Kansas Jayhawks football',         colors: ['#0051BA', '#E8000D', '#FFC82D', '#85898A'] },
  { id: 'cfb-kansas-state',      sport: 'college-football', league: 'Big 12', name: 'Kansas State Wildcats',   wikipediaTitle: 'Kansas State Wildcats football',   colors: ['#512888', '#D1D1D1', '#A7A7A7', '#000000', '#FFFFFF'] },
  { id: 'cfb-oklahoma-state',    sport: 'college-football', league: 'Big 12', name: 'Oklahoma State Cowboys',  wikipediaTitle: 'Oklahoma State Cowboys football',  colors: ['#FF7300', '#000000'] },
  { id: 'cfb-tcu',               sport: 'college-football', league: 'Big 12', name: 'TCU Horned Frogs',        wikipediaTitle: 'TCU Horned Frogs football',        colors: ['#4D1979', '#A3A9AC', '#FFFFFF'] },
  { id: 'cfb-texas-tech',        sport: 'college-football', league: 'Big 12', name: 'Texas Tech Red Raiders',  wikipediaTitle: 'Texas Tech Red Raiders football',  colors: ['#CC0000', '#000000'] },
  { id: 'cfb-ucf',               sport: 'college-football', league: 'Big 12', name: 'UCF Knights',             wikipediaTitle: 'UCF Knights football',             colors: ['#FFC904', '#BA9B37', '#000000'] },
  { id: 'cfb-utah',              sport: 'college-football', league: 'Big 12', name: 'Utah Utes',               wikipediaTitle: 'Utah Utes football',               colors: ['#CC0000', '#808080', '#000000'] },
  { id: 'cfb-west-virginia',     sport: 'college-football', league: 'Big 12', name: 'West Virginia Mountaineers', wikipediaTitle: 'West Virginia Mountaineers football', colors: ['#002855', '#EAAA00'] },

  // ============ American Athletic Conference ============
  { id: 'cfb-army',              sport: 'college-football', league: 'American', name: 'Army Black Knights',      wikipediaTitle: 'Army Black Knights football',      colors: ['#D4BF91', '#B2B4B3', '#000000'] },
  { id: 'cfb-charlotte',         sport: 'college-football', league: 'American', name: 'Charlotte 49ers',         wikipediaTitle: 'Charlotte 49ers football',         colors: ['#046A38', '#B9975B', '#27251F'] },
  { id: 'cfb-east-carolina',     sport: 'college-football', league: 'American', name: 'East Carolina Pirates',   wikipediaTitle: 'East Carolina Pirates football',   colors: ['#592A8A', '#FDC82F'] },
  { id: 'cfb-fau',               sport: 'college-football', league: 'American', name: 'Florida Atlantic Owls',   wikipediaTitle: 'Florida Atlantic Owls football',   colors: ['#003366', '#CC0000', '#8A8D8F', '#CCCCCC'] },
  { id: 'cfb-memphis',           sport: 'college-football', league: 'American', name: 'Memphis Tigers',          wikipediaTitle: 'Memphis Tigers football',          colors: ['#003087', '#898D8D', '#F8992E'] },
  { id: 'cfb-navy',              sport: 'college-football', league: 'American', name: 'Navy Midshipmen',         wikipediaTitle: 'Navy Midshipmen football',         colors: ['#00205B', '#C5B783'] },
  { id: 'cfb-north-texas',       sport: 'college-football', league: 'American', name: 'North Texas Mean Green',  wikipediaTitle: 'North Texas Mean Green football',  colors: ['#00853E', '#000000'] },
  { id: 'cfb-rice',              sport: 'college-football', league: 'American', name: 'Rice Owls',               wikipediaTitle: 'Rice Owls football',               colors: ['#00205B', '#C1C6C8'] },
  { id: 'cfb-south-florida',     sport: 'college-football', league: 'American', name: 'South Florida Bulls',     wikipediaTitle: 'South Florida Bulls football',     colors: ['#006747', '#CFC493'] },
  { id: 'cfb-temple',            sport: 'college-football', league: 'American', name: 'Temple Owls',             wikipediaTitle: 'Temple Owls football',             colors: ['#9D2235', '#FFCD00', '#8A8D8F', '#000000'] },
  { id: 'cfb-tulane',            sport: 'college-football', league: 'American', name: 'Tulane Green Wave',       wikipediaTitle: 'Tulane Green Wave football',       colors: ['#006747', '#43B02A', '#418FDE'] },
  { id: 'cfb-tulsa',             sport: 'college-football', league: 'American', name: 'Tulsa Golden Hurricane',  wikipediaTitle: 'Tulsa Golden Hurricane football',  colors: ['#002D72', '#C8102E', '#C5B783'] },
  { id: 'cfb-uab',               sport: 'college-football', league: 'American', name: 'UAB Blazers',             wikipediaTitle: 'UAB Blazers football',             colors: ['#006341', '#CC8A00', '#000000', '#BF0D3E'] },
  { id: 'cfb-utsa',              sport: 'college-football', league: 'American', name: 'UTSA Roadrunners',        wikipediaTitle: 'UTSA Roadrunners football',        colors: ['#F15A22', '#0C2340'] },

  // ============ Mid-American Conference ============
  { id: 'cfb-akron',             sport: 'college-football', league: 'MAC', name: 'Akron Zips',                  wikipediaTitle: 'Akron Zips football',                  colors: ['#041E42', '#A89968'] },
  { id: 'cfb-ball-state',        sport: 'college-football', league: 'MAC', name: 'Ball State Cardinals',        wikipediaTitle: 'Ball State Cardinals football',        colors: ['#BA0C2F'] },
  { id: 'cfb-bowling-green',     sport: 'college-football', league: 'MAC', name: 'Bowling Green Falcons',       wikipediaTitle: 'Bowling Green Falcons football',       colors: ['#FE5000', '#4F2C1D', '#CDA077'] },
  { id: 'cfb-buffalo',           sport: 'college-football', league: 'MAC', name: 'Buffalo Bulls',               wikipediaTitle: 'Buffalo Bulls football',               colors: ['#005BBB'] },
  { id: 'cfb-central-michigan',  sport: 'college-football', league: 'MAC', name: 'Central Michigan Chippewas',  wikipediaTitle: 'Central Michigan Chippewas football',  colors: ['#6A0032', '#FFC82E'] },
  { id: 'cfb-eastern-michigan',  sport: 'college-football', league: 'MAC', name: 'Eastern Michigan Eagles',     wikipediaTitle: 'Eastern Michigan Eagles football',     colors: ['#006633'] },
  { id: 'cfb-kent-state',        sport: 'college-football', league: 'MAC', name: 'Kent State Golden Flashes',   wikipediaTitle: 'Kent State Golden Flashes football',   colors: ['#002664', '#EAAB00'] },
  { id: 'cfb-umass',             sport: 'college-football', league: 'MAC', name: 'Massachusetts Minutemen',     wikipediaTitle: 'UMass Minutemen football',             colors: ['#971B2F', '#572932', '#B1B3B3'] },
  { id: 'cfb-miami-oh',          sport: 'college-football', league: 'MAC', name: 'Miami RedHawks',              wikipediaTitle: 'Miami RedHawks football',              colors: ['#B61E2E'] },
  { id: 'cfb-northern-illinois', sport: 'college-football', league: 'MAC', name: 'Northern Illinois Huskies',   wikipediaTitle: 'Northern Illinois Huskies football',   colors: ['#BA0C2F', '#8A8D8F'] },
  { id: 'cfb-ohio',              sport: 'college-football', league: 'MAC', name: 'Ohio Bobcats',                wikipediaTitle: 'Ohio Bobcats football',                colors: ['#00694E', '#CDA077'] },
  { id: 'cfb-toledo',            sport: 'college-football', league: 'MAC', name: 'Toledo Rockets',              wikipediaTitle: 'Toledo Rockets football',              colors: ['#15397F', '#005CB9', '#FFDA00', '#A0ACAA'] },
  { id: 'cfb-western-michigan',  sport: 'college-football', league: 'MAC', name: 'Western Michigan Broncos',    wikipediaTitle: 'Western Michigan Broncos football',    colors: ['#6C4023', '#B5A167', '#AAA8AA'] },

  // ============ Mountain West Conference ============
  { id: 'cfb-air-force',         sport: 'college-football', league: 'Mountain West', name: 'Air Force Falcons',     wikipediaTitle: 'Air Force Falcons football',     colors: ['#003087', '#8A8D8F'] },
  { id: 'cfb-boise-state',       sport: 'college-football', league: 'Mountain West', name: 'Boise State Broncos',   wikipediaTitle: 'Boise State Broncos football',   colors: ['#0033A0', '#D64309'] },
  { id: 'cfb-colorado-state',    sport: 'college-football', league: 'Mountain West', name: 'Colorado State Rams',   wikipediaTitle: 'Colorado State Rams football',   colors: ['#1E4D2B', '#C8C372'] },
  { id: 'cfb-fresno-state',      sport: 'college-football', league: 'Mountain West', name: 'Fresno State Bulldogs', wikipediaTitle: 'Fresno State Bulldogs football', colors: ['#DB0032', '#002E6D'] },
  { id: 'cfb-hawaii',            sport: 'college-football', league: 'Mountain West', name: 'Hawaii Rainbow Warriors', wikipediaTitle: 'Hawaii Rainbow Warriors football', colors: ['#024731', '#C8C8C8', '#000000'] },
  { id: 'cfb-nevada',            sport: 'college-football', league: 'Mountain West', name: 'Nevada Wolf Pack',      wikipediaTitle: 'Nevada Wolf Pack football',      colors: ['#003366', '#807F84'] },
  { id: 'cfb-new-mexico',        sport: 'college-football', league: 'Mountain West', name: 'New Mexico Lobos',      wikipediaTitle: 'New Mexico Lobos football',      colors: ['#BA0C2F', '#A7A8AA', '#63666A', '#007A86', '#000000'] },
  { id: 'cfb-san-diego-state',   sport: 'college-football', league: 'Mountain West', name: 'San Diego State Aztecs', wikipediaTitle: 'San Diego State Aztecs football', colors: ['#A6192E', '#000000'] },
  { id: 'cfb-san-jose-state',    sport: 'college-football', league: 'Mountain West', name: 'San Jose State Spartans', wikipediaTitle: 'San Jose State Spartans football', colors: ['#0055A2', '#E5A823', '#939597'] },
  { id: 'cfb-unlv',              sport: 'college-football', league: 'Mountain West', name: 'UNLV Rebels',           wikipediaTitle: 'UNLV Rebels football',           colors: ['#CF0A2C', '#CAC8C8', '#000000'] },
  { id: 'cfb-utah-state',        sport: 'college-football', league: 'Mountain West', name: 'Utah State Aggies',     wikipediaTitle: 'Utah State Aggies football',     colors: ['#00263A', '#8A8D8F', '#000000'] },
  { id: 'cfb-wyoming',           sport: 'college-football', league: 'Mountain West', name: 'Wyoming Cowboys',       wikipediaTitle: 'Wyoming Cowboys football',       colors: ['#FFC425', '#492F24'] },

  // ============ Sun Belt Conference ============
  { id: 'cfb-appalachian-state', sport: 'college-football', league: 'Sun Belt', name: 'Appalachian State Mountaineers', wikipediaTitle: 'Appalachian State Mountaineers football', colors: ['#FFCC00', '#000000'] },
  { id: 'cfb-arkansas-state',    sport: 'college-football', league: 'Sun Belt', name: 'Arkansas State Red Wolves',      wikipediaTitle: 'Arkansas State Red Wolves football',      colors: ['#CC092F', '#000000'] },
  { id: 'cfb-coastal-carolina',  sport: 'college-football', league: 'Sun Belt', name: 'Coastal Carolina Chanticleers',  wikipediaTitle: 'Coastal Carolina Chanticleers football',  colors: ['#006F71', '#A27752', '#111111'] },
  { id: 'cfb-georgia-southern',  sport: 'college-football', league: 'Sun Belt', name: 'Georgia Southern Eagles',        wikipediaTitle: 'Georgia Southern Eagles football',        colors: ['#011E41', '#A3AAAE', '#87714D'] },
  { id: 'cfb-georgia-state',     sport: 'college-football', league: 'Sun Belt', name: 'Georgia State Panthers',         wikipediaTitle: 'Georgia State Panthers football',         colors: ['#0039A6', '#C60C30', '#000000'] },
  { id: 'cfb-james-madison',     sport: 'college-football', league: 'Sun Belt', name: 'James Madison Dukes',            wikipediaTitle: 'James Madison Dukes football',            colors: ['#450084', '#CBB677'] },
  { id: 'cfb-louisiana',         sport: 'college-football', league: 'Sun Belt', name: "Louisiana Ragin' Cajuns",        wikipediaTitle: "Louisiana Ragin' Cajuns football",        colors: ['#CE181E', '#0A0203', '#C1C5C9'] },
  { id: 'cfb-louisiana-monroe',  sport: 'college-football', league: 'Sun Belt', name: 'Louisiana-Monroe Warhawks',      wikipediaTitle: 'Louisiana–Monroe Warhawks football',      colors: ['#840029', '#FDB913'] },
  { id: 'cfb-marshall',          sport: 'college-football', league: 'Sun Belt', name: 'Marshall Thundering Herd',       wikipediaTitle: 'Marshall Thundering Herd football',       colors: ['#00B140', '#A2AAAD', '#693F23', '#AD7C59', '#27251F'] },
  { id: 'cfb-old-dominion',      sport: 'college-football', league: 'Sun Belt', name: 'Old Dominion Monarchs',          wikipediaTitle: 'Old Dominion Monarchs football',          colors: ['#003057', '#7C878E', '#92C1E9'] },
  { id: 'cfb-south-alabama',     sport: 'college-football', league: 'Sun Belt', name: 'South Alabama Jaguars',          wikipediaTitle: 'South Alabama Jaguars football',          colors: ['#00205B', '#BF0D3E', '#FFFFFF'] },
  { id: 'cfb-southern-miss',     sport: 'college-football', league: 'Sun Belt', name: 'Southern Miss Golden Eagles',    wikipediaTitle: 'Southern Miss Golden Eagles football',    colors: ['#000000', '#FFAB00'] },
  { id: 'cfb-texas-state',       sport: 'college-football', league: 'Sun Belt', name: 'Texas State Bobcats',            wikipediaTitle: 'Texas State Bobcats football',            colors: ['#501214', '#8D734A'] },
  { id: 'cfb-troy',              sport: 'college-football', league: 'Sun Belt', name: 'Troy Trojans',                   wikipediaTitle: 'Troy Trojans football',                   colors: ['#8A2432', '#B3B5B8', '#FFFFFF'] },

  // ============ Conference USA ============
  { id: 'cfb-fiu',               sport: 'college-football', league: 'Conference USA', name: 'FIU Panthers',              wikipediaTitle: 'FIU Panthers football',              colors: ['#081E3F', '#D1A644', '#FFCC00'] },
  { id: 'cfb-jacksonville-state', sport: 'college-football', league: 'Conference USA', name: 'Jacksonville State Gamecocks', wikipediaTitle: 'Jacksonville State Gamecocks football', colors: ['#CC0000', '#FFFFFF', '#000000'] },
  { id: 'cfb-kennesaw-state',    sport: 'college-football', league: 'Conference USA', name: 'Kennesaw State Owls',       wikipediaTitle: 'Kennesaw State Owls football',       colors: ['#FDBB30', '#0B1315', '#C5C6C8'] },
  { id: 'cfb-liberty',           sport: 'college-football', league: 'Conference USA', name: 'Liberty Flames',            wikipediaTitle: 'Liberty Flames football',            colors: ['#002D62', '#C41230', '#C6C8CA'] },
  { id: 'cfb-louisiana-tech',    sport: 'college-football', league: 'Conference USA', name: 'Louisiana Tech Bulldogs',   wikipediaTitle: 'Louisiana Tech Bulldogs football',   colors: ['#002F8B', '#E31B23', '#A2AAAD', '#111111'] },
  { id: 'cfb-middle-tennessee',  sport: 'college-football', league: 'Conference USA', name: 'Middle Tennessee Blue Raiders', wikipediaTitle: 'Middle Tennessee Blue Raiders football', colors: ['#007BC3', '#343636', '#A6A8AA', '#004776'] },
  { id: 'cfb-new-mexico-state',  sport: 'college-football', league: 'Conference USA', name: 'New Mexico State Aggies',   wikipediaTitle: 'New Mexico State Aggies football',   colors: ['#8C0B42', '#FFFFFF'] },
  { id: 'cfb-sam-houston',       sport: 'college-football', league: 'Conference USA', name: 'Sam Houston Bearkats',      wikipediaTitle: 'Sam Houston Bearkats football',      colors: ['#FE5100', '#FFFFFF'] },
  { id: 'cfb-utep',              sport: 'college-football', league: 'Conference USA', name: 'UTEP Miners',               wikipediaTitle: 'UTEP Miners football',               colors: ['#FF8200', '#041E42', '#B1B3B3'] },
  { id: 'cfb-western-kentucky',  sport: 'college-football', league: 'Conference USA', name: 'Western Kentucky Hilltoppers', wikipediaTitle: 'Western Kentucky Hilltoppers football', colors: ['#C60C30', '#1E1E1E', '#A2A4A3'] },

  // ============ FBS Independents ============
  { id: 'cfb-notre-dame',        sport: 'college-football', league: 'Independent', name: 'Notre Dame Fighting Irish', wikipediaTitle: 'Notre Dame Fighting Irish football', colors: ['#0C2340', '#C99700', '#00843D'] },
  { id: 'cfb-uconn',             sport: 'college-football', league: 'Independent', name: 'UConn Huskies',             wikipediaTitle: 'UConn Huskies football',             colors: ['#000E2F', '#FFFFFF', '#7C878E'] },
];
